echo "#!/usr/bin/env zsh"
echo "#BSUB -J `basename $PWD`"
echo "#BSUB -o job%J-`basename $PWD`.stdout"
echo "#BSUB -e job%J-`basename $PWD`.stderr"
echo "#BSUB -u foerster@stce.rwth-aachen.de"
echo "#BSUB -N"
echo "#BSUB -R \"select[hpcwork]\""
echo "#BSUB -M 1020000"
#echo "#BSUB -W 3600"
echo "#BSUB -W 900"
echo "#BSUB -n 128"
echo "#BSUB -a \"bcs openmp\""
echo "#BSUB -x"
echo "echo \"Starting job at:\";"
echo "date;"
echo "unset OMP_THREAD_LIMIT;"
echo "export LD_LIBRARY_PATH=$HOME/lib:$LD_LIBRARY_PATH;"
echo "export SPLDIR=/home/mf510951/phd/code/compiler/spl-transformer"
echo "export PAPISRC=/home/mf510951/workspace/external-projects/papi-5.1.0/src"
echo "cd \$PAPISRC"
echo "make test"
echo "export testname=`basename $PWD`"
echo "export SPLcOnHPCWORK=\$HPCWORK/`basename \$SPLDIR`-job-\$RANDOM"
echo "rsync -av \$SPLDIR/ \$SPLcOnHPCWORK"
echo "export SPLDIR=\$SPLcOnHPCWORK"
echo "cd \$SPLcOnHPCWORK;"
echo "module unload gcc"
echo "module unload intel"
#echo "module load intel/13.1"
echo "module load gcc/4.8"
echo "rm -rf CMakeCache.txt CMakeFiles cmake_install*"
echo "cmake CMakeLists.txt && make;"
echo "cd test-suite;"
echo "rm -f hostconfig.txt"
echo "hostname >>  hostconfig.txt; echo >>  hostconfig.txt; echo >>  hostconfig.txt; echo >>  hostconfig.txt;"
echo "cat /proc/cpuinfo >>  hostconfig.txt; echo >>  hostconfig.txt; echo >>  hostconfig.txt; echo >>  hostconfig.txt;"
echo "cat /proc/meminfo >>  hostconfig.txt; echo >>  hostconfig.txt; echo >>  hostconfig.txt; echo >>  hostconfig.txt;"
echo "if [ \"\$testname\" != \"test-suite\" ]; then cd \$testname; fi"
echo "make clean ;"
echo "make scale_test_O3;"
echo "echo \"Finishing first scale test at:\"; date;";
echo ;
echo ;
echo "cd \$SPLcOnHPCWORK;"
echo "module unload gcc"
echo "module unload intel"
echo "module load intel/13.1"
echo "rm -rf CMakeCache.txt CMakeFiles cmake_install*"
echo "cmake CMakeLists.txt && make;"
echo "cd test-suite;"
echo "if [ \"\$testname\" != \"test-suite\" ]; then cd \$testname; fi"
echo "make clean ;"
echo "make scale_test;"
echo ;
echo ;
echo "echo \"Ending job at:\";"
echo "date;"
